sudo: required
services:
        - docker

before_install:
        - docker build -t tcesario/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true tcesario/docker-react npm run test
